### ISSUE TITLE
New-CmazIaaSVM  - Deployed VM's OS disk size doesn't occupy the allocated disk

### ISSUE THREAD

**Issue by eliot-trustm** [Trustmarque/cloudmarque-azure-pwsh#128]
The VM has a 128Gig disk, but inside the OS the C:\ drive is only 32Gb and needs to be manually expanded to grow into the available 128Gb Disk space
![image](https://user-images.githubusercontent.com/17768364/99563198-ec4f1f00-29c0-11eb-84d4-acf66ec123af.png)

**Comment by nathankitchen** [comment]
Likely depends on the image being used: https://docs.microsoft.com/en-us/azure/virtual-machines/windows/expand-os-disk

Not sure whether we want to address this as a bug as it appears to be expected behaviour. The user experience from the YML file isn't intuitive though: if we set the OS disk to a particular size then it's a reasonable expectation that the OS disk reports that size!

Is the ARM template disk size optional, reverting to the image size if not provided? If so, renaming the YML key that controls this to something like osDiskExpandableSize might make more sense, and set a better user expectation.

**Comment by tm-luke** [comment]
We will amend Yml property to osDiskExpandableSize.
