### ISSUE TITLE
New-CmAzCoreMonitor - Global Services (Action Groups) in separate RG to regional Services

### ISSUE THREAD

**Issue by JBiasilloTM** [Trustmarque/cloudmarque-azure-pwsh#187]
An enhancement is needed for multi-region deployments as currently duplicate Action Groups would be provisioned.  

Q: This could be considered a show stopper for multi-region deployments - so would extensions be used in this case?

If global services are already deployed then so need to be redeployed - i.e. New-CmAzCoreMonitor creates a duplicate Action Group resource in a different RG.  
Or should Global Services (e.g. core Action Groups) be deployed once in a separate RG for regional Services and reused as a cm-service dependency?
IMO Global Services should be deployed once in a separate RG for regional Services and reused - so perhaps a sperate command for Alters/alert groups?

**Comment by nathankitchen** [comment]
Thanks for raising these points, I believe they're tracked via other issues so this one will be closed. Relevant links are as follows: 

1. Action groups should be reused via service locator.
2. There's a separate issue raised to track how we deploy alerts, see issue #198 for details on the approach.
3. The naming convention clash has been closed by #195.

Where possible please modify a branched copy of Cloudmarque.Azure and submit it as a pull-request rather than building extensions, as these have to be managed back into the main codebase.
