### ISSUE TITLE
New-CmAzProject - Multi-project config

### ISSUE THREAD

**Issue by JBiasilloTM** [Trustmarque/cloudmarque-azure-pwsh#191]
New-CmAzProject copies a Project config.  The Project config is understandably aimed at unit/integration testing (e.g. arbitrary  settings values/names aimed at test configuration permutations rather then deploying a "model office" or reference architecture).

Suggest either:
1) modifying New-CmAzProject to support different configurations (e.g. -Name IntegrationTest, Hub-Spoke, DataSpoke etc.) add an option to -List available configurations 

Question: is cloudmarque-azure-pwsh the best place for project configurations? CloudmarqueExtensions is effectively being updated with sample "project" configurations. So perhaps leave New-CmAzProject as an internal integration test config and use CloudmarqueExtensions (at least until CloudmarqueExtensions is assimilated) ?

**Comment by nathankitchen** [comment]
New-CmAzProject is designed to create a new configuration project. It's used by our CI/CD processes as the basis for a deployable "model office", largely as a way to confirm that the shipping examples will stand up a real environment. It currently skips a couple of packed templates including things like WVD, but is otherwise reasonably complete.

As a piece of functionality it's philosophy is the same as `dotnet new` ([link](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-new)), so your idea of several template ideas fits well. These would roughly map to folders within the /resources/ folder.

To put a bit of meat on this, I think the request here is as follows:

- Move the existing CI/CD baseline in `/Resources/Project` to `/Resources/Projects/ModelOffice`
- Add `-ListAvailable` parameter to `New-CmAzProject` which lists the directories in `/Resources/Projects/`
- Add a `-Name` parameter to `New-CmAzProject` which delivers the existing functionality, namely copying out the contents of the named directory.

This will need specific validation on the `-Name` parameter to make sure you can't inject different paths, e.g. by passing a name of "..\..\Public" to copy out the public folder. There's no security issue there, but it's not what's supposed to happen: `-Name` **must** match the name of a single folder in the `Resources\Projects` directory.

I'm dropping the 'question' tag and dropping this into the next milestone as it seems like a reasonably straightforward bit of plumbing.
